### ISSUE TITLE
Crash with QWIK v1.9.1: document is not defined

### ISSUE THREAD

**Issue by AlreNux** [wmertens/styled-vanilla-extract#31]
An error occurs when viewing the “styled-flower” page:
```
[vite] Internal server error: document is not defined
      at Module.injectStyles (C:\Users\Spell\Desktop\test-qwik-vanilla\node_modules\@vanilla-extract\css\injectStyles\dist\vanilla-extract-css-injectStyles.cjs.dev.js:14:19)
      at inject (C:\Users\Spell\Desktop\test-qwik-vanilla\src\routes\styled-flower\flower.css.ts.vanilla.js:3:25)
      at C:\Users\Spell\Desktop\test-qwik-vanilla\src\routes\styled-flower\flower.css.ts.vanilla.js:8:1
      at async instantiateModule (file:///C:/Users/Spell/Desktop/test-qwik-vanilla/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5)
```

**How to repeat:**
1. Initiate the project using the “bun create qwik” command
2. Install “bun install” dependencies
3. Install “styled-vanilla-extract” library via “bun run qwik add styled-vanilla-extract” command

**File Contents:**
There is no provision for any modifications made by hand.

vite.config.ts
```
import { vanillaExtractPlugin } from "styled-vanilla-extract/vite";
...
plugins: [qwikCity(), qwikVite(), tsconfigPaths(), vanillaExtractPlugin()],
```

**Error screenshot:**
![image](https://github.com/user-attachments/assets/d2da816d-442d-4678-8c67-eeb4c31c2351)

**Repository screenshot:**
![image](https://github.com/user-attachments/assets/b7c78526-94e6-4f8c-865e-c6e4d7934120)

P.S.
If you put another vanilla-extract plugin for vite - “@vanilla-extract/vite-plugin”, this error disappears
![image](https://github.com/user-attachments/assets/56ec6e1c-a9f2-44a0-9b59-2f5be031499d)

**Comment by wmertens** [comment]
PRs or new maintainers welcome - I'm not using this package any more, and it seems like vanilla got their vite game in order, so this package is really only providing the styled interface.
